# Generated by Django 5.1.7 on 2025-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_enquiry_budget_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
